version: '3.8'

services:
  redis:
    image: redis
    command: redis-server --requirepass asdf
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh -c "pnpm install && pnpm run start"
    restart: always
    ports:
      - 8080:8080
    working_dir: /app
    depends_on:
      - redis
    environment:
      - VIRTUAL_HOST=reservation.t65k2.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=reservation.t65k2.com
      - LETSENCRYPT_EMAIL=steedude@gmail.com
    networks:
      - internal_network
      - external_network

networks:
  internal_network:
    driver: bridge
  external_network:
    external:
      name: shared_network
